# .travis.yml for r-travis.
#
# If you're looking to use r-travis with your project, DO NOT USE THIS
# FILE -- use `sample.travis.yml` instead.

language: r
r: bioc-devel
cache: packages
warnings_are_errors: false
sudo: false
before_install:
  - tlmgr install bera
  - tlmgr install nowidow
  - tlmgr install parnotes
  - tlmgr install marginfix
r_packages:
  - devtools
