# .travis.yml for r-travis.
#
# If you're looking to use r-travis with your project, DO NOT USE THIS
# FILE -- use `sample.travis.yml` instead.

language: r
r: bioc-devel
cache: packages
warnings_are_errors: true
sudo: required
before_install:
 - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
 - chmod 755 ./travis-tool.sh
 - ./travis-tool.sh bootstrap
install:
 - ./travis-tool.sh github_package Bohdan-Khomtchouk/gtf
r_github_packages:
 - Bohdan-Khomtchouk/gtf
apt_packages: bedtools

